steps:
  # Step 1: Build the Docker image (Using $COMMIT_SHA for dynamic tagging)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/qwiklabs-gcp-01-35487e0f15c0/cloud-run-source-deploy/inventory-api:$COMMIT_SHA'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-east1-docker.pkg.dev/qwiklabs-gcp-01-35487e0f15c0/cloud-run-source-deploy/inventory-api:$COMMIT_SHA'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'inventory-api'
      - '--image'
      - 'us-east1-docker.pkg.dev/qwiklabs-gcp-01-35487e0f15c0/cloud-run-source-deploy/inventory-api:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'

images:
  - 'us-east1-docker.pkg.dev/qwiklabs-gcp-01-35487e0f15c0/cloud-run-source-deploy/inventory-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY